### ISSUE TITLE
Remove unecessary Show and Eq instances

### ISSUE THREAD

**Issue by tobbebex** [sedillard/Vec#1]
GHC 7.4 has removed Eq and Show as superclasses to Num which is great for the design of DSLs like GPipe. However, many functions in the Vec library still requires Eq and/or Show instances, eg identity and multmm. I guess the Eq instances are needed for many of the cases, but I cant see any reason for the Show requirements.

**Comment by sedillard** [comment]
It's been a while since I've had my head in this code, so maybe it's me but I don't understand what changes you're suggesting. The identity and multmm functions don't explicitly require Eq or Show. They may be indirectly required by way of the Num constraints, because Num explicitly requires Eq and Show. Two people independently submitted patches to add Eq and Show constraints to the Num and Fractional instances in Vec, specifically to address breakage on 7.4, so I'm not sure how to proceed here.

https://github.com/sedillard/Vec/commit/fa685e97b591409e6ace3389d6bc174754354a22

**Comment by tobbebex** [comment]
The thing is that Num class doesnt require Eq or Show anymore, so I guess there is some other function that explicitly require them, possibly not in the Vec library itself but maybe imported, even from Prelude. I'll have a look at the code and see if I can track down where those constraints are introduced.
